-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('STUDENT', 'ADMIN', 'SUPER_ADMIN', 'DEPARTMENT', 'CLEARANCE_OFFICER', 'POLICE_OFFICER', 'LIBRARY_OFFICER', 'DORMITORY_OFFICER', 'FACULTY_OFFICER', 'SPORTS_OFFICER', 'STUDENT_DEAN_OFFICER') NOT NULL;
